language: ruby
rvm:
  - 2.3.0-p0
services:
  - elasticsearch
  - postgresql
addons:
  postgresql: "9.6"
dist: trusty
before_script:
  - sleep 10
  - psql -c 'create database piste_test;' -U postgres
env:
  - ES_VERSION=5.4.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - export RAILS_ENV=test
  - rails db:create db:schema:load db:test:prepare
  - rspec spec